### PR TITLE
Change wording of main page and add Hacktually section

### PR DESCRIPTION
**Pull request by kiawildberger**
New feature:
- Changes main page wording away from recruitment to Hacktually
- Adds a proper section for Hacktually information (linking to community discord)
- Solves for #4 

Should look good on mobile too. Tested on Firefox and Safari but I'm not doing anything fancy that should cause cross browser issues.

Screenshot 2024-10-18 at 10 01 08

Screenshot 2024-10-18 at 10 01 28

### CODE REVIEW

**Comment by Lin-Jet** [comment]
really good! I love the blobs and the hover effect :)

some things i want ot add though, 
Screen Shot 2024-10-21 at 11 22 48 PM
change the apply now to learn more and link to the hacktually section you made

change upper left wording "UC Merced COB2 110, 130 and 140
Saturday, November 2nd 10am-6pm
Food will be available at noon" to 

"Saturday Nov. 2nd 10am - 6pm, at UC Merced COB2 130
Food available at noon."

change "Learn CSS, UI/UX, NodeJS, React, Git, Bash, Firebase and more!" to
"Workshop schedule coming soon!" make this the bottom right one 

have the join our discord be the bottom left one

have the blobs bigger? 


finally, have the hacktually sectoin above the tracks so it goes mainpage and then right below is hacktually section

**Comment by kiawildberger** [comment]
Ok, I've added these suggestions and resolved conflicts from the other PRs that got merged.

**Comment by Lin-Jet** [comment]
ok thats perfect! just a few small tweaks...

the learn more button on the main page does not have the stars

i think the fix is put this back
```
<a className="registerButton2Stars" href="https://docs.google.com/forms/d/e/1FAIpQLSd7K6NUy1IWhxdTOlP_40LQLvO-9S1cIRlE_KQlPj6xkFf3dg/viewform?usp=sf_link">
                  <button className="registerButton2">Apply Now!</button>
                  
                  <div className="starWrapper">
                    <p className="star1" id="star">★</p>
                    <p className="star2" id="star">★</p>
                    <p className="star3" id="star">★</p>
                  </div>
                  <div className="starBursts">
                    <p className="starBurst1">✨</p>
                    <p className="starBurst2">⭐️</p>
                    <p className="starBurst3">🌟</p>
                  </div>
                 
                  
                </a>
```

and the ninstead of hte registration form link it to href="./#hacktually" change the to learn more as well


also for the hacktually button in the navbar, when in mobile view the hacktualyl text goes outof the button.

the chagne is probably something in line 696 to 702 within the @media screen mobile view section
.registerButton{
    border-radius: 3rem;
    padding: 0.5rem;
    text-align: center;
    font-size: 1em;
    width: 4rem;
  } change is probably make the width: 4rem to a hgiher value.. like 5rem lol.  a more ideal fix is make it scale to hacktually text but not required.

**Comment by kiawildberger** [comment]
The stars animation seems to be broken, even on the live site, and I'd rather get the hacktually website working its publicity magic if we're going to completely redesign the website anyways. I used the `fit-content` rule to fix the button in the navbar.

**Comment by Lin-Jet** [comment]
I agree that we should prioritize getting the Hacktually advertisement section running, especially with the upcoming redesign in mind. Regarding the stars animation, if you think it's not worth fixing for now, we can revisit it during the redesign phase

I also saw the fit-content change for the navbar button—thanks for that update

**Pull request merged**
